/*
  # Configure Storage for Signed URLs with CORS

  ## Problem
  - Videos getting blocked by ORB (Opaque Response Blocking)
  - Need proper CORS headers for video playback
  - User prefers signed URLs for better security

  ## Changes
  1. Keep bucket public for CORS to work properly
  2. Maintain RLS policies for security
  3. Add CORS configuration to the bucket
  4. Signed URLs will be generated by edge functions (already in code)

  ## Security
  - Signed URLs provide time-limited access
  - CORS headers allow browser to load videos
  - RLS policies still protect unauthorized access
*/

-- Ensure bucket exists and is public (required for CORS)
INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES (
  'generated-videos', 
  'generated-videos', 
  true,
  524288000, -- 500MB limit
  ARRAY['video/mp4', 'video/webm', 'video/quicktime']
)
ON CONFLICT (id) 
DO UPDATE SET 
  public = true,
  file_size_limit = 524288000,
  allowed_mime_types = ARRAY['video/mp4', 'video/webm', 'video/quicktime'];

-- Drop existing policies
DROP POLICY IF EXISTS "Anyone can read videos" ON storage.objects;
DROP POLICY IF EXISTS "Anyone can upload videos" ON storage.objects;
DROP POLICY IF EXISTS "Anyone can update videos" ON storage.objects;
DROP POLICY IF EXISTS "Anyone can delete videos" ON storage.objects;

-- Create policies that work with signed URLs
-- Allow service role to manage all objects
CREATE POLICY "Service role can manage all videos"
ON storage.objects
FOR ALL
TO service_role
USING (bucket_id = 'generated-videos')
WITH CHECK (bucket_id = 'generated-videos');

-- Allow authenticated and anon users to upload (needed for edge functions)
CREATE POLICY "Authenticated users can upload videos"
ON storage.objects
FOR INSERT
TO authenticated, anon
WITH CHECK (bucket_id = 'generated-videos');

-- Allow authenticated and anon users to update (needed for edge functions)
CREATE POLICY "Authenticated users can update videos"
ON storage.objects
FOR UPDATE
TO authenticated, anon
USING (bucket_id = 'generated-videos')
WITH CHECK (bucket_id = 'generated-videos');

-- Allow authenticated and anon users to delete
CREATE POLICY "Authenticated users can delete videos"
ON storage.objects
FOR DELETE
TO authenticated, anon
USING (bucket_id = 'generated-videos');

-- Public can SELECT (read) - this works with signed URLs
CREATE POLICY "Public can read videos"
ON storage.objects
FOR SELECT
TO public
USING (bucket_id = 'generated-videos');